### ISSUE TITLE
Hard to see what's selected in Scene Tree + Script Editor

### ISSUE THREAD

**Issue by npinsker** [passivestar/godot-minimal-theme#12]
I love this theme a lot, but after switching I had a lot of trouble telling which node in the scene tree was selected. The contrast between the selection and other nodes wasn't enough for me. Just personal taste of course; filing in case it's useful for anyone else.

I changed a line to improve this:
```
// Tree/styles/selected = SubResource("StyleBoxFlat_32au3")
// -> [sub_resource type="StyleBoxFlat" id="StyleBoxFlat_32au3"]

< bg_color = Color(1, 1, 1, 0.0392157)
---
> bg_color = Color(0.5, 0.4, 1, 0.28)
```
but there's likely a better color out there.

**Comment by passivestar** [comment]
Increase contrast for selected items in b007c6e4d9f3e6674706f4c00970bb89c14f0f47

<img width="577" alt="s" src="https://github.com/user-attachments/assets/d38a1a8d-6d82-45df-82b7-9d7ea0ef3b6c">
