### ISSUE TITLE
Input/Button sizes are not consistant

### ISSUE THREAD

**Issue by Shadowblitz16** [passivestar/godot-minimal-theme#13]
This clone button here...
![image](https://github.com/user-attachments/assets/a73acb2d-4450-47dc-90a0-6e29c472ea53)

The Scene item vs the Add metadata or Script dropdown here
![image](https://github.com/user-attachments/assets/ff7938f4-7503-4a3c-a366-4d4319365238)

**Comment by Shadowblitz16** [comment]
> Close button doesn't seem to have the right paddings in your screenshot, is there a chance you're using a high ppi version with regular editor scale?
> <img alt="image" width="155" src="https://private-user-images.githubusercontent.com/60579014/387000476-69ca49ad-2e76-435b-8bf6-b2d4042c1523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzI1NTcsIm5iZiI6MTczMjA3MjI1NywicGF0aCI6Ii82MDU3OTAxNC8zODcwMDA0NzYtNjljYTQ5YWQtMmU3Ni00MzViLThiZjYtYjJkNDA0MmMxNTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAzMTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0OTg0OTcyYzRhMDg3ZGMwYTQ5NmU4YzBmZTU3ZmNjNjA3ZTYzZDcyYjBlNTFhZjZlNTNjYzA0YWJiMzcxOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6UrvCLSFp3K9w1pSNApbhP3wVnjFlIQuJO4q2Hc96Qw">
> 
> If by scene item you mean the height of the node item (World) it's not supposed to have the same height as buttons because it's not a button, it's a tree item, you need to fit a lot of them on screen
> 
> As for the inconsistency of heights of inputs in inspector or settings it is something that I'd like to fix but it's not possible without patching things on the editor side. The height of text inputs was reduced to help working with data-heavy resources in inspector (essentially making it look more like a list in terms of spacing). But it's not easy to reduce the height of checkbox inputs or dropdowns

Idk I stopped using this theme for a while now so I forgot. I was never using anything above hd resolution though so I doubt it

**Comment by passivestar** [comment]
The theme has been reworked entirely for 2.0.0, margins are now calculated dynamically and should be correct regardless of screen dpi, and also margins can be adjusted through the "Base Spacing" setting now. So it should work, if you try this theme again and it doesn't this can be reopened
