### ISSUE TITLE
Version 2.X isn't working (Godot 4.4 Dev 7, macOS 15.2)

### ISSUE THREAD

**Issue by OscarCookeAbbott** [passivestar/godot-minimal-theme#16]
Just decided to try the theme after downloading Godot 4.4 and the theme v2.0.1 doesn't do anything and v2.0.0 throws a GDScript error on assigning and then does nothing. Restarting etc doesn't do anything. I haven't used the theme in year or so, maybe macOS is interfering with the new resource GDScript implementation or something?

**Comment by passivestar** [comment]
> and v2.0.0 throws a GDScript error on assigning

what's the error?

**Comment by OscarCookeAbbott** [comment]
Just tried with both versions again and it is** also logged by v2.0.1** on assigning to the input (after a brief freeze as it presumably executes):

`GDScript_hhmc0:447 - Parse Error: Values of the ternary operator are not mutually compatible. (Warning treated as error.)`

**Comment by passivestar** [comment]
I see, this seems to be due to gdscript warnings config in your project. You can try loading a new empty godot project to confirm that that's the case.

This might take some time to fix because it will fail on more than that ternary, I will need to rewrite the whole thing to ensure full type safety. Will probably do it today

**Comment by OscarCookeAbbott** [comment]
Ah yeah that makes sense. Apologies but I forgot to test in a blank new project until now and it _does_ work there (I'm gonna blame it being late in my timezone...). I've not overridden any theme settings etc so no idea why it doesn't work in my actual project but I'll just have to figure it out.

**Comment by passivestar** [comment]
Like I said I'll need to fix theme's code for it to work in all projects, this is not a user error. Even though it happens only with certain project settings and even though it doesn't necessarily make sense that project settings affect the theme, it's something that I *can fix* so I'll keep this issue open until I do

**Comment by passivestar** [comment]
Let me know if this works
https://github.com/passivestar/godot-minimal-theme/blob/main/minimal_theme.tres

**Comment by OscarCookeAbbott** [comment]
Yep seems to work fine with the ternary error checking back on, and my other GDScript safety settings on.
