### ISSUE TITLE
Better Tutorial Video Suggestion

### ISSUE THREAD

**Issue by ArtcadeDev** [passivestar/godot-minimal-theme#5]
[This Video](https://youtu.be/7Bqm1Oqm4gc?si=h1xqrWbYINbFgvjv) is a straight-to-the-point tutorial on how to set up the theme in under 1 minute, it's much more efficient.

**Comment by passivestar** [comment]
Unfortunately at no point that video shows my theme

Here's a side by side comparison of this theme and godot's default theme:

![image](https://github.com/passivestar/godot-minimal-theme/assets/60579014/f1d2b1dd-2322-46c7-9e68-bd32075a318e)

**Comment by TokisanGames** [comment]
If you make a theme resource in the inspector, it will bring up the bottom theme panel which shows a bunch of UI elements: tabs, buttons, sliders, line edits, etc.
