### ISSUE TITLE
Tileset editor paint properties dropdown background is using clear color

### ISSUE THREAD

**Issue by Gnumaru** [passivestar/godot-minimal-theme#7]
Using orange as clear color

![image](https://github.com/passivestar/godot-minimal-theme/assets/5783414/043ed2f5-7bcd-424d-9ec8-bd78cc70b364)

without any custom theme

![image](https://github.com/passivestar/godot-minimal-theme/assets/5783414/ca029dda-522f-43f2-a223-0719f486111e)

with the minimal theme master branch 

![image](https://github.com/passivestar/godot-minimal-theme/assets/5783414/ded1b519-75ad-42c4-9676-7da983784a75)

**Comment by passivestar** [comment]
Fixed with https://github.com/godotengine/godot/pull/93609

I didn't get to theming that part of the editor yet to make it look more polished, but at least that popup is not broken anymore
